monitor=,preferred,auto,1

exec-once = waybar & swww init

input {
    kb_layout = us
    follow_mouse = 1
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

decoration {
    rounding = 10
}

animations {
    enabled = yes
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_is_master = true
}

misc {
    force_default_wallpaper = 0
}

bind = SUPER, Q, exec, me-terminal
bind = SUPER, C, killactive, 
bind = SUPER, M, exit, 
bind = SUPER, E, exec, dolphin
bind = SUPER, V, togglefloating, 
bind = SUPER, R, exec, rofi -show drun
bind = SUPER, P, pseudo, # dwindle
bind = SUPER, J, togglesplit, # dwindle

# Move focus with mainMod + arrow keys
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
